In [3]:
import numpy as np
import pandas as pd
import os

# M1 T02: Data exploration and structure - Dataframes with Pandas
Description

Familiarize yourself with data exploration techniques using the data structure, Dataframe with the Pandas library.
Level 1



# - Exercises 1

Download the Airlines Delay: Airline on-time statistics and delay causes data set and upload it to a Dataframe pandas. Explore the data it contains, and keep only the columns you consider relevant.


In [4]:
# Exercises 1
# Download the Airlines Delay: Airline on-time statistics and delay causes data set and upload it to a Dataframe pandas. Explore the data it contains, and keep only the columns you consider relevant.
df = pd.read_csv(
    os.path.realpath('.') + "/archive/DelayedFlights_simple.csv",
    # os.path.realpath('.') + "/archive/DelayedFlights.csv",
    usecols = ['Year', 'Month', 'DayofMonth', 'Distance', 'AirTime', 'DepTime', 'CRSDepTime'])
print(df)

    Year  Month  DayofMonth  DepTime  CRSDepTime  AirTime  Distance
0   2008      1           3   2003.0        1955    116.0     810.0
1   2008      1           3    754.0         735    113.0     810.0
2   2008      1           3    628.0         620     76.0     515.0
3   2008      1           3   1829.0        1755     77.0     515.0
4   2008      1           3   1940.0        1915     87.0     688.0
5   2008      1           3   1937.0        1830    230.0    1591.0
6   2008      1           3    706.0         700    106.0     828.0
7   2008      1           3   1644.0        1510    107.0     828.0
8   2008      1           3   1029.0        1020     37.0     162.0
9   2008      1           3   1452.0        1425    213.0    1489.0
10  2008      1           3    754.0         745    205.0    1489.0
11  2008      1           3   1323.0        1255    110.0     838.0
12  2008      1           3   1416.0        1325     49.0     220.0
13  2008      1           3   1657.0        1625

### Exercises 2

Make a complete report of the date set:
  - Summarize the columns of interest statistically
  - Find how many missing data are per column
  - Create new columns (average flight speed, whether late or not ...)
  - Table of airlines with the most accumulated arrears
  - What are the longest flights? And the most backward?
  - Etc.


In [14]:
def get_report(df: pd.DataFrame) -> dict:
    ''' Find how many missing data are per column '''
    results = {} 
    results['stats'] = calc_stats(df)  
    results['speed_min'] = calc_speed(df)  
    # return {'speed_max': 123}
    return results

def calc_stats(df) -> dict:
    ''' Summarize the columns of interest statistically'''
    stats = {}
    stats['total_rows'] = df.shape[0]
    stats['missing_values'] = df.isnull().sum().sum()
    print(df.isnull().sum())
    print(stats['missing_values'])
    return stats

def calc_speed(df: pd.DataFrame) -> pd.DataFrame:
    ''' Create new columns (average flight speed, whether late or not ...) '''
    df['speed'] = df['Distance']/df['AirTime'] 
    # df.apply(lambda row: row['Distance']/row['AirTime']),
    #                      axis = 1)
    # print(df['speed'])
    speed_min = df['speed'].loc[df['speed'].idxmin()] 
    # print(speed_min)
    return speed_min


def test_get_report(df):
    # assert get_report(df) == 123
    assert get_report(df)['speed_min'] == 4.378378378378378
    assert get_report(df)['stats']['missing_values'] == 4
test_get_report(df)

Year          0
Month         0
DayofMonth    0
DepTime       0
CRSDepTime    0
AirTime       1
Distance      1
speed         2
dtype: int64
4
Year          0
Month         0
DayofMonth    0
DepTime       0
CRSDepTime    0
AirTime       1
Distance      1
speed         2
dtype: int64
4


### Exercises 3

Export the data set clean and with the new columns to Excel.


Create a function that given a two-dimensional table, calculates the totals per row and the totals per column.

In [133]:
def random_couple() -> Tuple[int, int]:
    return (6,8)
     #        n = np.random.randint(1,6)
     #    arr = random_n_square(n)

def totals_2D(n):
    ''' given a two-dimensional table, calculates the totals per row and the totals per column '''
    ax_0, ax_1 = random_couple()
    arr = np.random.randint(0, 2, [ax_0, ax_1])
    print(arr)
    return np.sum(arr, axis = 1), np.sum(arr, axis = 0)
    
print(totals_2D(5))

[[1 0 1 1 0 1 1 1]
 [1 0 0 1 1 0 1 0]
 [0 0 1 1 1 0 0 1]
 [1 0 1 0 1 0 0 0]
 [1 1 0 1 1 0 1 1]
 [0 1 0 1 0 1 1 1]]
(array([6, 4, 4, 3, 6, 5]), array([4, 2, 3, 5, 4, 2, 4, 4]))


### Exercises 4

Manually implements a function that calculates the correlation coefficient. Learn about its uses and interpretation.

[boston](https://sphweb.bumc.bu.edu/otlt/MPH-Modules/PH717-QuantCore/PH717-Module9-Correlation-Regression/PH717-Module9-Correlation-Regression4.html)


    


In [ ]:
def Cov(X,Y) is the covariance, i.e., how far each observed (X,Y) pair is from the mean of X and the mean of Y, simultaneously, and and sx2 and sy2 are the sample variances for X and Y.

def calc_correlation():
     ''' return the correlation coefficient '''
        
        
        

def test_calc_correlation():
     ''' return the correlation coefficient '''

        . Learn about its uses and interpretation. 