In [1]:
import numpy as np
import pytest
import pandas as pd
# import sys
import os


# M1 T02: Data exploration and structure - Dataframes with Pandas
Description

Familiarize yourself with data exploration techniques using the data structure, Dataframe with the Pandas library.
Level 1

# - Exercises 1

Download the Airlines Delay: Airline on-time statistics and delay causes data set and upload it to a Dataframe pandas. Explore the data it contains, and keep only the columns you consider relevant.


In [2]:
os.getcwd()
# dirname = os.path.dirname(__file__)
# filename = os.path.join(dirname, 'relative/path/to/file/you/want')

import sys,os
print(sys.path.append(os.path.realpath('..')))

None


In [3]:

import io
import pandas as pd
input_file = list(uploader.value.values())[0]
content = input_file['content']
content = io.StringIO(content.decode('utf-8'))
df = pd.read_csv(content)
df.head()

NameError: name 'uploader' is not defined

In [5]:
# Exercises 1

# Download the Airlines Delay: Airline on-time statistics and delay causes data set and upload it to a Dataframe pandas. Explore the data it contains, and keep only the columns you consider relevant.


# df = pd.read_csv("/home/su/workspace/python/ciencia_dades_python/CDP_M1_T01_numpy/archive/DelayedFlights.csv")

#  df_2 = pd.read_csv('archive/DelayedFlights.csv', sep=', ', delimiter=None, header='infer', names=None, index_col=None,)
df = pd.read_csv(sys.path + "archive/DelayedFlights.csv")


TypeError: can only concatenate list (not "str") to list

In [11]:
df

Unnamed: 0  Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  \
0                 0  2008      1           3          4   2003.0        1955   
1                 1  2008      1           3          4    754.0         735   
2                 2  2008      1           3          4    628.0         620   
3                 4  2008      1           3          4   1829.0        1755   
4                 5  2008      1           3          4   1940.0        1915   
...             ...   ...    ...         ...        ...      ...         ...   
1936753     7009710  2008     12          13          6   1250.0        1220   
1936754     7009717  2008     12          13          6    657.0         600   
1936755     7009718  2008     12          13          6   1007.0         847   
1936756     7009726  2008     12          13          6   1251.0        1240   
1936757     7009727  2008     12          13          6   1110.0        1103   

         ArrTime  CRSArrTime UniqueCarrier  ...  TaxiIn TaxiOut  Cancelled  \
0         2211.0        2225            WN  ...     4.0     8.0          0   
1         1002.0        1000            WN  ...     5.0    10.0          0   
2          804.0         750            WN  ...     3.0    17.0          0   
3         1959.0        1925            WN  ...     3.0    10.0          0   
4         2121.0        2110            WN  ...     4.0    10.0          0   
...          ...         ...           ...  ...     ...     ...        ...   
1936753   1617.0        1552            DL  ...     9.0    18.0          0   
1936754    904.0         749            DL  ...    15.0    34.0          0   
1936755   1149.0        1010            DL  ...     8.0    32.0          0   
1936756   1446.0        1437            DL  ...    13.0    13.0          0   
1936757   1413.0        1418            DL  ...     8.0    11.0          0   

         CancellationCode  Diverted  CarrierDelay  WeatherDelay NASDelay  \
0                       N         0           NaN           NaN      NaN   
1                       N         0           NaN           NaN      NaN   
2                       N         0           NaN           NaN      NaN   
3                       N         0           2.0           0.0      0.0   
4                       N         0           NaN           NaN      NaN   
...                   ...       ...           ...           ...      ...   
1936753                 N         0           3.0           0.0      0.0   
1936754                 N         0           0.0          57.0     18.0   
1936755                 N         0           1.0           0.0     19.0   
1936756                 N         0           NaN           NaN      NaN   
1936757                 N         0           NaN           NaN      NaN   

        SecurityDelay  LateAircraftDelay  
0                 NaN                NaN  
1                 NaN                NaN  
2                 NaN                NaN  
3                 0.0               32.0  
4                 NaN                NaN  
...               ...                ...  
1936753           0.0               22.0  
1936754           0.0                0.0  
1936755           0.0               79.0  
1936756           NaN                NaN  
1936757           NaN                NaN  

[1936758 rows x 30 columns]

In [105]:
# tests
a0 = np.array([])
a1 = np.array([[0, 1, 1], [1, 0, 1], [1, 1, 0]])  
a2 = np.array([0, 1, 1])  
a3 = np.array([0, 1, 1, 1, 5.56, 1])
values = [a0, a1, a2, a3]
results = ["Array dimention error", "Array dimention error", 0.66667, 1.59333]
cases = zip(values, results)

def test_array_stat(cases):
    for val, res in cases: 
        if not isinstance(array_stat(val), str):
            assert array_stat(val)['mean'] == res
        
test_array_stat(cases)

In [106]:
# other way to provide and check the result
def array_stat_2(arr: np.array) -> dict:
    if arr.size == 0 or 1 < len(arr.shape): 
        # return print("Array dimention error") 
        return {'status': "Array dimention error"}
    else:
        res = {
            'status': 'ok',
            'mean': round(np.mean(arr), 5),
            'max': round(np.max(arr), 5),
            'min': round(np.min(arr), 5),
        }        
        return res


array_stat_2(a3)


{'status': 'ok', 'mean': 1.59333, 'max': 5.56, 'min': 0.0}

In [107]:
results = ["Array dimention error", "Array dimention error", 0.66667, 1.59333]
cases = zip(values, results)

def test_array_stat_2(cases):
    for val, res in cases: 
        # if (ouput:= res['status']) == 'ok':
        output = array_stat_2(val)
        if output['status'] == 'ok':
            assert output['mean'] == res
        else:
            assert output['status'] == "Array dimention error"
        
test_array_stat_2(cases)

### Exercises 2

Make a complete report of the date set:
  - Summarize the columns of interest statistically
  - Find how many missing data are per column
  - Create new columns (average flight speed, whether late or not ...)
  - Table of airlines with the most accumulated arrears
  - What are the longest flights? And the most backward?
     Etc.


In [127]:
def get_report(df: pd.DataFrame) -> str:
    def random_n_square(n: int = 6) -> np.array:
    return np.random.uniform(33, 66, [n, n])
    # return round(np.random.uniform(33.33, 66.66, [n, n]), 2)
    # Returns a random float number up to 2 decimal places    

print(random_n_square(4))

def test_random_n_square():
    for _ in range(5):
        n = np.random.randint(1,6)
        arr = random_n_square(n)
        assert np.size(arr) == n**2

test_random_n_square()

[[38.13626351 44.80526296 49.7207901  33.72228294]
 [65.74671823 58.71582603 46.75819609 49.40745914]
 [65.22393626 65.72357685 62.58486766 51.15707167]
 [44.56327936 61.62704017 46.2366861  49.90935233]]


### Exercises 3

Export the data set clean and with the new columns to Excel.


Create a function that given a two-dimensional table, calculates the totals per row and the totals per column.

In [133]:
def random_couple() -> Tuple[int, int]:
    return (6,8)
     #        n = np.random.randint(1,6)
     #    arr = random_n_square(n)

def totals_2D(n):
    ''' given a two-dimensional table, calculates the totals per row and the totals per column '''
    ax_0, ax_1 = random_couple()
    arr = np.random.randint(0, 2, [ax_0, ax_1])
    print(arr)
    return np.sum(arr, axis = 1), np.sum(arr, axis = 0)
    
print(totals_2D(5))

[[1 0 1 1 0 1 1 1]
 [1 0 0 1 1 0 1 0]
 [0 0 1 1 1 0 0 1]
 [1 0 1 0 1 0 0 0]
 [1 1 0 1 1 0 1 1]
 [0 1 0 1 0 1 1 1]]
(array([6, 4, 4, 3, 6, 5]), array([4, 2, 3, 5, 4, 2, 4, 4]))


### Exercises 4

Manually implements a function that calculates the correlation coefficient. Learn about its uses and interpretation.

[boston](https://sphweb.bumc.bu.edu/otlt/MPH-Modules/PH717-QuantCore/PH717-Module9-Correlation-Regression/PH717-Module9-Correlation-Regression4.html)


    


In [ ]:
def Cov(X,Y) is the covariance, i.e., how far each observed (X,Y) pair is from the mean of X and the mean of Y, simultaneously, and and sx2 and sy2 are the sample variances for X and Y.

def calc_correlation():
     ''' return the correlation coefficient '''
        
        
        

def test_calc_correlation():
     ''' return the correlation coefficient '''

        . Learn about its uses and interpretation. 