In [5]:
import numpy as np
from  typing import Union, Tuple

# Exercises 1

Create a function that, given an array of one dimension, gives you a basic statistical summary of the data. If it detects that the array has more than one dimension, it should display an error message.

In [19]:
def array_stat(arr: np.array, precision=5) -> Union[dict, str]:
    if arr.size == 0 or 1 < len(arr.shape): 
        # return print("Array dimention error") 
        return ("Array dimention error")
    else:
        res = {
            'max': round(np.max(arr), precision),
            'min': round(np.min(arr), precision),
            'mean': round(np.mean(arr), precision),
            'sd': round(np.std(arr), precision),
        }        
        return res

In [20]:
# tests
a0 = np.array([])
a1 = np.array([[0, 1, 1], [1, 0, 1], [1, 1, 0]])  
a2 = np.array([0, 1, 1])  
a3 = np.array([0, 1, 1, 1, 5.56, 1])
values = [a0, a1, a2, a3]
results = ["Array dimention error", "Array dimention error", 0.66667, 1.59333]
cases = zip(values, results)

def test_array_stat(cases):
    for val, res in cases: 
        if not isinstance(array_stat(val), str):
            assert array_stat(val)['mean'] == res
        
test_array_stat(cases)

In [21]:
# other way to provide and check the result
def array_stat_2(arr: np.array) -> dict:
    if arr.size == 0 or 1 < len(arr.shape): 
        # return print("Array dimention error") 
        return {'status': "Array dimention error"}
    else:
        res = {
            'status': 'ok',
            'mean': round(np.mean(arr), 5),
            'max': round(np.max(arr), 5),
            'min': round(np.min(arr), 5),
        }        
        return res


array_stat_2(a3)


{'status': 'ok', 'mean': 1.59333, 'max': 5.56, 'min': 0.0}

In [23]:
results = ["Array dimention error", "Array dimention error", 0.66667, 1.59333]
cases = zip(values, results)

def test_array_stat_2(cases) -> None:
    for val, res in cases: 
        # if (ouput:= res['status']) == 'ok':
        output = array_stat_2(val)
        if output['status'] == 'ok':
            assert output['mean'] == res
        else:
            assert output['status'] == "Array dimention error"
        
test_array_stat_2(cases)

# Exercises 2
Create a function that generates an NxN square of random numbers between 0 and 100.



In [25]:
def random_n_square(n: int = 6) -> np.array:
    return np.random.uniform(33, 66, [n, n])
    # return round(np.random.uniform(33.33, 66.66, [n, n]), 2)
    # Returns a random float number up to 2 decimal places    

print(random_n_square(4))

def test_random_n_square():
    for _ in range(5):
        n = np.random.randint(1,6)
        arr = random_n_square(n)
        assert np.size(arr) == n**2

test_random_n_square()

[[53.7730826  33.63816386 47.93702566 45.4607994 ]
 [55.39256195 65.91287598 44.604051   63.49730821]
 [62.74147723 58.29479965 59.92872074 39.05076107]
 [43.54961924 54.24687951 41.39259068 48.73138649]]


# Exercises 3
Create a function that given a two-dimensional table, calculates the totals per row and the totals per column.

In [10]:
def get_random_pair() -> Tuple[int, int]:
    return np.random.randint(10), np.random.randint(10)
     #    arr = random_n_square(n)

def get_random_2D_arr(min = 0, max = 2, dim = get_random_pair()) -> np.array:
    return np.random.randint(min, max, dim)

def totals_2D(arr = get_random_2D_arr()) -> Tuple[int, int]:
    ''' given a two-dimensional table, calculates the totals per row and the totals per column '''
    print(arr)
    return np.sum(arr, axis = 1), np.sum(arr, axis = 0)

def test_totals_2D():
    A = np.array([
        [1, 0, 0, 1, 1, 0, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 1],
        [1, 1, 1, 0, 1, 0, 0, 0],
        [0, 1, 0, 1, 1, 0, 1, 1],
        [0, 1, 0, 1, 1, 1, 1, 1],
        [0, 1, 0, 1, 0, 1, 0, 0]])
    assert totals_2D(A) == (np.array([5, 1, 4, 5, 6, 3]), np.array([2, 4, 1, 4, 4, 2, 3, 4]))

# Exercises 4

Manually implements a function that calculates the correlation coefficient. Learn about its uses and interpretation.

[boston](https://sphweb.bumc.bu.edu/otlt/MPH-Modules/PH717-QuantCore/PH717-Module9-Correlation-Regression/PH717-Module9-Correlation-Regression4.html)

[realpython](https://realpython.com/numpy-scipy-pandas-correlation-python/)


    


In [31]:
def calc_cov(X,Y):
     ''' return the covariance, i.e., how far each observed (X,Y) pair is from 
         the mean of X and the mean of Y, simultaneously, and and sx2 and sy2 are the sample variances for X and Y.'''


def calc_correlation(arr_1, arr_2):
     ''' return the correlation coefficient '''
     n = np.size(arr_1)
     if (len(np.shape(arr_1)) > 1 or len(np.shape(arr_2)) > 1 or 
         np.size(arr_1) != np.size(arr_2)):
         return False
     else:
          num = n*np.multiply(arr_1, arr_2) - np.sum(arr_1)*np.sum(arr_2)
          denom = np.sqrt((n*np.sum(np.square(arr_1)) - np.sum(arr_1)**2 ) *  
                          (n*np.sum(np.square(arr_2)) - np.sum(arr_2)**2 ))

          correlation = num / denom
          print(correlation)
          print(np.corrcoef(arr_1, arr_2)[0][1])
          return correlation   
          # np.shape(arr_1)) > 1 or len(np.shape(arr_2)

a = np.array( [1,2,3,4,5,6]               )  #[0, 1, 2, 2])
b = np.array( [2,4,7,9,12,14]       )  #[1, 4, 2, 7])

calc_correlation(a,b)


          
# def test_calc_correlation_2D():
#      ''' return the correlation coefficient '''
#      A = get_random_2D_arr()
#      B = get_random_2D_arr(dim=np.shape(A))
#      print(np.corrcoef(A,B))
#      return True


# def test_calc_correlation():
#      ''' return the correlation coefficient '''
     
#      # case complementay matrix

#      c_00 = np.array([0, 0, 1, 1, 1, 1,])
#      c_01 = np.array([1, 1, 0, 0, 0, 0,]) 
#      correl_0 = np.corrcoef(c_00, c_01) # TODO switch to custom func 
#      print(correl_0)
#      assert correl_0[0][0] == 1
#      assert correl_0[0][1] == -1

#      c_10 = np.array([0, 0, 1, 1, 1, 1,])
#      c_11 = np.array([1, 1, 1, 1, 1, 1,]) 
#      correl_1 = np.corrcoef(c_10, c_11)
#      print(correl_1)
#      # assert correl_1[0][0] == 1
#      # assert correl_1[0][1] == -1


#      # A = np.random.randint(2, size=6)
#      # B = np.random.randint(2, size=6)
#      # np.random.randint(0, 9, 4)   
#      # print(A, B)
#      # print(np.corrcoef(A,B))
#      # correl_0 = np.corrcoef(A,B) # TODO switch to custom func 
#      # # print(np.corrcoef(A,A,rowvar=0))
#      # assert correl_0[0][0] == 1


test_calc_correlation()

[-2.30283093 -1.77646958 -1.77646958 -0.46056619]
0.592156525463792
[[ 1. -1.]
 [-1.  1.]]
[[ 1. nan]
 [nan nan]]
